[package]
name = "geogroup_gui"
description = "A tool to easily organize photos into folders based on their location"
version = "0.1.0"
edition = "2021"

[dependencies]
geogroup_backend = { path = "../backend" }
eframe = "0.29.1"
egui_extras = { version = "0.29.1", features = ["all_loaders"] }
image = { version = "0.25", features = ["jpeg", "png"] }
env_logger = { version = "0.10", default-features = false, features = [
    "auto-color",
    "humantime",
] }
rfd = "0.15.0"
egui_inbox = "0.5.0"
chrono = "0.4.38"
clap = { version = "4.5.22", features = ["cargo", "derive", "env"] }
