[package]
name = "geogroup_algo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_hierarchy = { path = "../lazy_hierarchy" }
itertools = "0.14.0"
log = "0.4.27"
geogroup_common = { path = "../common", default-features = false }
take_mut = "0.2.2"

[features]
debug_colors = ["lazy_hierarchy/colors"]


[dev-dependencies]
lazy_hierarchy = { path = "../lazy_hierarchy", features = ["colors"] }
